Add All Controls benchmark
turbot/steampipe-mod-azure-compliance pull request #212
Opened 2023-08-16 13:28 UTC by khushboo9024

### Checklist
- [ ] Issue(s) linked

2023-08-30 10:33 UTC, madhushreeray30 reviewed
@khushboo9024 please have a look at the comments, thanks!

2023-08-30 10:33 UTC, madhushreeray30 commented on controls_by_service/search.sp
Should we rename this file to `cognitivesearch.sp`?

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/appservice.sp
> +  title       = "Ensure App Service Authentication is set up for apps in Azure App Service"
```suggestion
  title       = "Ensure App Service authentication is set up for apps in Azure App Service"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/appservice.sp
> +  description = "Azure App Service Authentication is a feature that can prevent anonymous HTTP requests from reaching a Web Application or authenticate those with tokens before they reach the app. If
```suggestion
  description = "Azure App Service authentication is a feature that can prevent anonymous HTTP requests from reaching a Web Application or authenticate those with tokens before they reach the app. If an anonymous request is received from a browser, App Service will redirect to a logon page. To handle the logon process, a choice from a set of identity providers can be made, or a custom authentication mechanism can be implemented."
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/iam.sp
> +  title       = "Ensure That No Custom Subscription Administrator Roles Exist"
```suggestion
  title       = "Ensure that no Custom Subscription Administrator roles exist"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/iam.sp
> +  title       = "Ensure Multi-factor Authentication is Required for Azure Management"
```suggestion
  title       = "Ensure Multi-factor Authentication is required for Azure Management"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/iam.sp
> +  title       = "Ensure That 'Users Can Register Applications' Is Set to 'No'"
```suggestion
  title       = "Ensure that 'Users Can Register Applications' is set to 'No'"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/monitor.sp
> +  description = "The storage account container containing the activity log export should not be publicly accessible."
```suggestion
  title       = "Ensure the storage container storing the operational logs is not publicly accessible"
  description = "The storage account container containing the operational log export should not be publicly accessible."
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/mysql.sp
> +  description = "Enable audit_log_enabled on MySQL Servers."
```suggestion
  description = "Enable audit logging on MySQL Servers."
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/network.sp
> +  title       = "Ensure an Azure Bastion Host Exists"
```suggestion
  title       = "Ensure an Azure Bastion Host exists"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/securitycenter.sp
> +  title       = "Ensure That Microsoft Defender for Azure Cosmos DB Is Set To 'On'"
```suggestion
  title       = "Ensure That Microsoft Defender for Azure Cosmos DB is set to 'On'"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/securitycenter.sp
> +  title       = "Ensure That Microsoft Defender for Databases Is Set To 'On'"
```suggestion
  title       = "Ensure That Microsoft Defender for Databases is set to 'On'"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/securitycenter.sp
> +  title       = "Ensure That Microsoft Defender for Open-Source Relational Databases Is Set To 'On'"
```suggestion
  title       = "Ensure That Microsoft Defender for Open-Source Relational Databases is set to 'On'"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/securitycenter.sp
> +  title       = "Ensure that Microsoft Defender for Cloud Apps (MCAS) Integration with Microsoft Defender for Cloud is Selected"
```suggestion
  title       = "Ensure that Microsoft Defender for Cloud Apps (MCAS) Integration with Microsoft Defender for Cloud is selected"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/storage.sp
> +  description = "The Storage Blob service provides scalable, cost-efficient objective storage in the cloud. Storage Logging happens server-side and allows details for both successful and failed reque
```suggestion
  description = "The Storage Blob service provides scalable, cost-efficient objective storage in the cloud. Storage Logging happens server-side and allows details for both successful and failed requests to be recorded in the storage account. These logs allow users to see the details of read, write, and delete operations against the blobs. Storage Logging log entries contain the following information about individual requests: Timing information such as start time, end-to-end latency, and server latency, authentication details, concurrency information, and the sizes of the request and response messages."
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/storage.sp
> +  title       = "Ensure Storage Logging is Enabled for Table Service for 'Read', 'Write', and 'Delete' Requests "
```suggestion
  title       = "Ensure Storage Logging is Enabled for Table Service for 'Read', 'Write', and 'Delete' requests"
```

2023-08-30 10:33 UTC, madhushreeray30 commented on regulatory_compliance/storage.sp
> +  description = "The Storage Queue service stores messages that may be read by any client who has access to the storage account. A queue can contain an unlimited number of messages, each of which can
```suggestion
  description = "The Storage Queue service stores messages that may be read by any client who has access to the storage account. A queue can contain an unlimited number of messages, each of which can be up to 64KB in size using version 2011-08-18 or newer. Storage Logging happens server-side and allows details for both successful and failed requests to be recorded in the storage account. These logs allow users to see the details of read, write, and delete operations against the queues. Storage Logging log entries contain the following information about individual requests: Timing information such as start time, end-to-end latency, and server latency, authentication details, concurrency information, and the sizes of the request and response messages."
```

2023-08-30 13:32 UTC, cbruno10 requested changes
@khushboo9024 Please see comments, thanks!

2023-08-30 13:32 UTC, cbruno10 commented on controls_by_service/controls_by_service.sp
> +  description = "This benchmark contains all controls grouped by service to help you detect resource configurations that do not meet best practices."
```suggestion
benchmark "all_controls" {
  title       = "All Controls"
  description = "This benchmark contains all controls grouped by service to help you detect resource configurations that do not meet best practices."
```

2023-08-30 13:32 UTC, cbruno10 commented on controls_by_service/controls_by_service.sp
> +  controls_by_service_common_tags = merge(local.azure_compliance_common_tags, {
```suggestion
  all_controls_common_tags = merge(local.azure_compliance_common_tags, {
```

2023-08-30 13:32 UTC, cbruno10 commented on controls_by_service/controls_by_service.sp
> +    benchmark.controls_by_service_activedirectory,
```suggestion
    benchmark.all_controls_activedirectory,
```

Please make the changes for other benchmark names too, thanks!

2023-08-31 11:42 UTC, madhushreeray30 approved these changes

2023-08-31 11:43 UTC, misraved approved these changes

2023-08-31 11:49 UTC, merged